org: thriftyx
service: backend

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev 

plugins:
  - serverless-offline

custom:
  serverless-offline:
    useStage: false

functions:
  api:
    handler: handler.api
    timeout: 90
    events:
      - http:
          path: /{proxy+}
          method: any
