const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const User = new Schema({
    name:{
        type:String,
        unique:false,
        default:null,
        required:false
    },
    email:{
        type:String,
        default:null,
        required:false
    },
    phone:{
        type:String,
        default:null,
        required:false
    },
    profilePicture:{
        type:String,
        unique:false,
        default:null,
        required:false
    },
    city:{
        type:String,
        unique:false,
        default:null,
        required:false
    },
    DOB:{
        type:Date,
        unique:false,
        required:false
    },
    gender:{
        type:String,
        unique:false,
        default:null,
        required:false
    },
    password:{
        type:String,
        unique:false,
        required:false
    },
    token:{
        type:String,
        unique:false,
        required:false
    },
    otp:{
        type:String,
        unique:false,
        required:false
    },
    createdBy:{
        type:Date,
        unique:false,
        required:false
    },
    isVerified:{
        type:Boolean,
        unique:false,
        required:false
    },
    registrationId:{
        type:String,
        unique:false,
        required:false
    },
    forgotCode:{
        type:String,
        unique:false,
        required:false
    }
});
module.exports = mongoose.model("users",User);